# quotes.py

QUOTES = [
    ("The obstacle is the way.", "Marcus Aurelius"),
    ("Love your fate. It is strength.", "Marcus Aurelius"),
    ("Memento Mori. Remember you will die.", "Stoic Proverb"),
    ("Focus only on what you control.", "Epictetus"),
    ("Through hardship, to the stars.", "Seneca"),
    ("Character is your destiny.", "Heraclitus"),
    ("Master your mind, master your life.", "Epictetus"),
    ("Waste no more time. Be good.", "Marcus Aurelius"),
    ("The best revenge is to be unlike your enemy.", "Marcus Aurelius"),
    ("Difficulties strengthen the mind.", "Seneca"),
    ("You have power over your mind, not outside events.", "Marcus Aurelius"),
    ("We suffer more in imagination than in reality.", "Seneca"),
    ("First, say who you are. Then, do the work.", "Epictetus"),
    ("Luck is what happens when preparation meets opportunity.", "Seneca"),
    ("A gem cannot be polished without friction.", "Seneca"),
    ("To improve, risk looking foolish.", "Epictetus"),
    ("Be tolerant with others and strict with yourself.", "Marcus Aurelius"),
    ("No great thing is created suddenly.", "Epictetus"),
    ("He who fears death will never do anything worthy.", "Seneca"),
    ("The only constant in life is change.", "Heraclitus"),
    ("It’s not what happens, but how you react that matters.", "Epictetus"),
    ("Anger hurts you more than the injury.", "Seneca"),
    ("If it is not right, do not do it.", "Marcus Aurelius"),
    ("Wealth is having few wants.", "Epictetus"),
    ("Associate with people who are likely to improve you.", "Seneca"),
    ("Your will is always within your power.", "Epictetus"),
    ("The soul is dyed by its thoughts.", "Marcus Aurelius"),
    ("Time heals what reason cannot.", "Seneca"),
    ("Choose not to be harmed, and you won't feel harmed.", "Marcus Aurelius"),
    ("Don't explain your philosophy. Embody it.", "Epictetus"),
    ("Hang on to your youthful enthusiasms, you’ll be able to use them better when you’re older.", "Seneca"),
    ("The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"),
    ("It does not matter what you bear, but how you bear it.", "Seneca"),
    ("Objective judgment, now, at this very moment.", "Marcus Aurelius"),
    ("All cruelty springs from weakness.", "Seneca"),
    ("Confine yourself to the present.", "Marcus Aurelius"),
    ("Silence is a lesson learned from the many sufferings of life.", "Seneca"),
    ("What stands in the way becomes the way.", "Marcus Aurelius"),
    ("A smooth sea never made a skilled sailor.", "Proverb"),
    ("Control your perceptions.", "Stoic Maxim"),
    ("Direct your actions properly.", "Stoic Maxim"),
    ("Willingly accept what's outside your control.", "Stoic Maxim"),
    ("The man who craves more is poor.", "Seneca"),
    ("Dwell on the beauty of life.", "Marcus Aurelius"),
    ("You could leave life right now.", "Marcus Aurelius"),
    ("True happiness is to enjoy the present.", "Seneca"),
    ("If you want to be a writer, write.", "Epictetus"),
    ("Death smiles at us all; all we can do is smile back.", "Marcus Aurelius"),
    ("Every new beginning comes from some other beginning's end.", "Seneca"),
    ("It's a rough road that leads to the heights of greatness.", "Seneca"),
    ("Look to the past to see the future.", "Marcus Aurelius"),
    ("The greatest remedy for anger is delay.", "Seneca"),
    ("We are disturbed not by things, but by the views we take of them.", "Epictetus"),
    ("A gift consists not in what is done or given, but in the intention of the giver or doer.", "Seneca"),
    ("Ask yourself at every moment, 'Is this necessary?'", "Marcus Aurelius"),
    ("Man is not worried by real problems so much as by his imagined anxieties about real problems.", "Epictetus"),
    ("Life is long if you know how to use it.", "Seneca"),
    ("Very little is needed for a happy life.", "Marcus Aurelius"),
    ("The whole future lies in uncertainty: live immediately.", "Seneca"),
    ("Make the best use of what is in your power, and take the rest as it happens.", "Epictetus"),
    ("The universe is change; our life is what our thoughts make it.", "Marcus Aurelius"),
    ("Religion is regarded by the common people as true, by the wise as false, and by rulers as useful.", "Seneca"),
    ("The trials you encounter will introduce you to your strengths.", "Seneca"),
    ("How does it help…to make troubles heavier by bemoaning them?", "Seneca"),
    ("Cease worrying about things which are beyond the power of our will.", "Epictetus"),
    ("He who is brave is free.", "Seneca"),
    ("Get active in your own rescue.", "Marcus Aurelius"),
    ("It is the power of the mind to be unconquerable.", "Seneca"),
    ("Small-minded people blame others. Average people blame themselves. The wise see all blame as foolishness.", "Epictetus"),
    ("They lose the day in expectation of the night, and the night in fear of the dawn.", "Seneca"),
    ("You have been formed of three parts—body, breath, and mind. Of these, the first two are yours only so far as you must take care of them. The third alone is truly yours.", "Marcus Aurelius"),
    ("Nothing is more honorable than a grateful heart.", "Seneca"),
    ("Only the educated are free.", "Epictetus"),
    ("As long as you live, keep learning how to live.", "Seneca"),
    ("If a man knows not which port he sails, no wind is favorable.", "Seneca"),
    ("You don't have forever. Act accordingly.", "Marcus Aurelius"),
    ("I am not born for one corner; the whole world is my native land.", "Seneca"),
    ("Circumstances don't make the man, they only reveal him to himself.", "Epictetus"),
    ("Begin at once to live, and count each separate day as a separate life.", "Seneca"),
    ("If it is not true, do not say it.", "Marcus Aurelius"),
    ("While we wait for life, life passes.", "Seneca"),
    ("People are not disturbed by things, but by the view they take of them.", "Epictetus"),
    ("Wherever there is a human being, there is an opportunity for a kindness.", "Seneca"),
    ("The one who puts the finishing touches on their life each day is never short of time.", "Marcus Aurelius"),
    ("Let us say what we feel, and feel what we say; let speech harmonize with life.", "Seneca"),
    ("In short, know this: Human beings have been designed to bear nearly any ill, so long as they can assure themselves that it is necessary.", "Epictetus"),
    ("It is a denial of justice not to stretch out a helping hand to the fallen; that is the common right of humanity.", "Seneca"),
    ("The first step: Don’t be anxious.", "Marcus Aurelius"),
    ("You can’t control the wind, but you can adjust your sails.", "Proverb"),
    ("The more we value things outside our control, the less control we have.", "Epictetus"),
    ("Life is a play. It's not its length, but its performance that counts.", "Seneca"),
    ("From the ashes, a fire shall be woken.", "J.R.R. Tolkien"),
    ("The mind that is anxious about future events is miserable.", "Seneca"),
    ("Be like the rock that the waves keep crashing over. It stands unmoved and the raging of the sea falls still around it.", "Marcus Aurelius"),
    ("It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.", "Seneca"),
    ("When you are offended at any man's fault, turn to yourself and study your own failings.", "Epictetus"),
    ("The final hour of greatness is that we can choose to be greater than our suffering.", "Proverb"),
]